#!/usr/bin/env bash

usage() {
  cat <<'EOF'
Run install scripts in install.d/ by name

Usage: install [--dry] [name...]
       install [--dry] --all

Options:
  --all   run every script in install.d/
  --dry   show what will be done
EOF
}

if [[ $# -eq 0 ]]; then
  usage
  exit 0
fi

root_dir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"

all=""
dry=""
names=()

while [[ $# -gt 0 ]]; do
  if [[ "$1" == "--dry" ]]; then
    dry="1"
  elif [[ "$1" == "--all" ]]; then
    all="1"
  else
    names+=("$1")
  fi
  shift
done

scripts=$(find "${root_dir}/install.d/" -type f -executable)

matched=()
if [[ $all != "1" ]]; then
  for s in $scripts; do
    for name in "${names[@]}"; do
      s_name=$(basename $s)
      if [[ "${s_name,,}" == *"${name,,}"* ]]; then
        matched+=("$s")
        break
      fi
    done
  done
else
  matched=$scripts[@];
fi

for s in "${matched[@]}"; do
  if [[ $dry == "1" ]]; then
    echo "[DRY] will run ${s}"
  else
    $s
  fi
done
