- hosts: localhost
  connection: local
  become: yes
  vars:
    config: "{{ lookup('env', 'HOME') }}/.config/nvim"
  tasks:
    - name: Create config folder
      file:
        path: "{{ config }}"
        state: directory
        mode: '0755'

    - name: Copy ./dotfiles/nvim to ~/.config/nvim
      copy:
        src: "../dotfiles/nvim/"
        dest: "{{ config }}"
        mode: '0755'
