- name: Install i3 window manager locally
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Update apt repo and cache on localhost
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install i3 window manager
      ansible.builtin.apt:
        name: i3
        state: present
        
    - name: Ensure ~/.config/i3 directory exists
      ansible.builtin.file:
        path: ~/.config/i3
        state: directory
    
    - name: Copy config file to config folder
      ansible.builtin.copy:
        src: "../dotfiles/i3/config"
        dest: "{{ ansible_env.HOME }}/.config/i3/config"
        mode: "0777"

    - name: Install feh image viewer so I can set wallpaper
      ansible.builtin.apt:
      name: feh
      state: present
