#!/usr/bin/env bash

VERSION="0.11.0"
OUT="$HOME/.local/bin/nvim"

sudo apt install -y fuse
mkdir -p ~/.local/bin/

curl -L -o "${OUT}" \
    "https://github.com/neovim/neovim/releases/download/v${VERSION}/nvim-linux-x86_64.appimage"
chmod +x "${OUT}"
