#!/usr/bin/env bash

# releases -- https://github.com/tree-sitter/tree-sitter/releases
VERSION="0.25.3"
OUT="$HOME/.local/bin/tree-sitter"

mkdir -p ~/.local/bin/
curl -L -o "${OUT}.gz" \
    "https://github.com/tree-sitter/tree-sitter/releases/download/v${VERSION}/tree-sitter-linux-x64.gz"
gunzip -f "${OUT}.gz"
chmod +x "${OUT}"
